Repository compucorp/civihr, pull requests merged in 2018-02, with the labels that each got.

#2462 PCHR-3267: Fix leave widget errors
  com.civicrm.hrjobroles/js/dist/job-roles.min.js
  contactaccessrights/js/dist/access-rights.min.js
  contactsummary/js/dist/contact-summary.min.js
  hrjobcontract/js/dist/job-contract.min.js
  org.civicrm.reqangular/dist/reqangular.min.js
  uk.co.compucorp.civicrm.appraisals/js/dist/appraisals.min.js
  uk.co.compucorp.civicrm.hrcore/gulp/tasks/requirejs.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-notification-badge.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-widget/leave-widget-absence-types-amount-taken.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-widget/leave-widget-absence-types-available-balance.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-widget/leave-widget-next-leave.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-widget/leave-widget.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-widget/leave-widget-absence-types-amount-taken.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-widget/leave-widget-absence-types-available-balance.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-widget/leave-widget-next-leave.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-widget/leave-widget.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-widget/leave-widget-next-leave.html
Labels: bug, ready to test

#2464 PCHR-3259: Use lint staged for pre-commit linters
  .githooks/pre-commit
  package-lock.json
  package.json
Labels: enhancement, ready to test

#2458 PCHR-3190: Sort Absence Types in Leave Staff Report
  contactsummary/js/dist/contact-summary.min.js
  hrjobcontract/js/dist/job-contract.min.js
  hrjobcontract/js/src/job-contract/services/contract-leave.service.js
  hrjobcontract/js/test/services/contract-leave.service.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/apis/absence-type.api.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-balance-tab.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-calendar.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-widget/leave-widget.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/staff-leave-report.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/request.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/apis/absence-type.api.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-balance-tab.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-calendar.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-widget/leave-widget.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/staff-leave-report.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/request.controller.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-balance-tab-filters.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/partials/staff-leave-report-requests-rows.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/staff-leave-report.html
Labels: enhancement, ready to test, regression

#2454 PCHR-3233: Make maximum deduction base on selected time or timeframe
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-request-popup-details-tab.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/data/leave-request.data.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-request-popup-details-tab.component.spec.js
Labels: enhancement, ready to test

#2471 PCHR-3276: Remove data from the hrabsence extension
  uk.co.compucorp.civicrm.hrsampledata/CRM/HRSampleData/Cleaner/AbsenceType.php
  uk.co.compucorp.civicrm.hrsampledata/CRM/HRSampleData/Importer/AbsencePeriod.php
  uk.co.compucorp.civicrm.hrsampledata/CRM/HRSampleData/Importer/AbsenceType.php
  uk.co.compucorp.civicrm.hrsampledata/CRM/HRSampleData/Importer/JobContract.php
  uk.co.compucorp.civicrm.hrsampledata/CRM/HRSampleData/Upgrader.php
  uk.co.compucorp.civicrm.hrsampledata/resources/csv/civicrm_activity.csv
  uk.co.compucorp.civicrm.hrsampledata/resources/csv/civicrm_hrabsence_period.csv
  uk.co.compucorp.civicrm.hrsampledata/resources/csv/civicrm_hrabsence_type.csv
  uk.co.compucorp.civicrm.hrsampledata/sql/uninstall.sql
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/BaseCSVProcessorTest.php
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/Cleaner/AbsenceTypeTest.php
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/Importer/AbsencePeriodTest.php
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/Importer/AbsenceTypeTest.php
Labels: bug, ready to test

#2470 PCHR-3074: Display Contact Access Rights Info on Contact Actions Menu
  contactaccessrights/CRM/Contactaccessrights/BAO/Rights.php
  contactaccessrights/CRM/Contactaccessrights/Component/ContactActionsMenu/GenericListItem.php
  contactaccessrights/CRM/Contactaccessrights/Component/ContactActionsMenu/GroupTitleToolTipItem.php
  contactaccessrights/CRM/Contactaccessrights/Component/ContactActionsMenu/NoStaffToolTipItem.php
  contactaccessrights/CRM/Contactaccessrights/Helper/ContactActionsMenu/ContactAccessActionGroup.php
  contactaccessrights/CRM/Contactaccessrights/Service/ACL.php
  contactaccessrights/api/v3/Rights/Getlocations.php
  contactaccessrights/api/v3/Rights/Getregions.php
  contactaccessrights/contactaccessrights.php
  contactaccessrights/tests/phpunit/BaseHeadlessTest.php
  contactaccessrights/tests/phpunit/CRM/Contactaccessrights/BAO/RightsTest.php
  contactaccessrights/tests/phpunit/CRM/Contactaccessrights/Helper/ContactActionsMenu/ContactAccessGroupTest.php
  contactaccessrights/tests/phpunit/CRM/Contactaccessrights/Service/ACLTest.php
  contactaccessrights/tests/phpunit/CRM/Contactaccessrights/Utils/ACLTest.php
  contactaccessrights/tests/phpunit/bootstrap.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Component/GenericToolTipItem.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Component/NoUserTextItem.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Component/ParagraphItem.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Helper/UserInformationActionGroup.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/templates/CRM/HRContactActionsMenu/Page/Inline/Actions.tpl
  uk.co.compucorp.civicrm.hrcontactactionsmenu/tests/phpunit/CRM/HRContactActionsMenu/Helper/UserInformationActionGroupTest.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Component/ContactActionsMenu/NoSelectedLineManagerTextItem.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Helper/ContactActionsMenu/WorkflowActionGroup.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Helper/ContactActionsMenu/WorkflowActionGroupTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Component/ContactActionsMenu/NoSelectedLeaveApproverItem.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Helper/ContactActionsMenu/LeaveActionGroup.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Helper/ContactActionsMenu/LeaveActionGroupTest.php
Labels: ready to test

#2456 PCHR-3251: Upgrader for single day requests in hours
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1018.php
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-calendar-day.html
Labels: enhancement, ready to test

#2473 PCHR-3246: Implement stylelint for SASS files
  package-lock.json
  package.json
Labels: ready to test

#2475 PCHR-3285: Redirect from the SSP report pages to the CiviHR admin
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Page/Reports.php
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Page/Reports.tpl
  uk.co.compucorp.civicrm.hrcore/xml/Menu/hrcore.xml
Labels: enhancement, ready to test

#2477 PCHR-3291: Rename Communications Menu Title
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Helper/CommunicationActionGroup.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/tests/phpunit/CRM/HRContactActionsMenu/Helper/CommunicationActionGroupTest.php
Labels: ready to test

#2476 PCHR-3286: Rename Contact Access Rights menu group title
  contactaccessrights/CRM/Contactaccessrights/Helper/ContactActionsMenu/ContactAccessActionGroup.php
  contactaccessrights/tests/phpunit/CRM/Contactaccessrights/Helper/ContactActionsMenu/ContactAccessGroupTest.php
Labels: ready to test

#2479 PCHR-2592: Reporting UX improvements
  hrui/CRM/HRUI/Upgrader/Steps/4701.php
  hrui/hrui.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Page/Reports.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1007.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/js/crm/vendor/iframeResizer.min.js
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Page/Reports.tpl
  uk.co.compucorp.civicrm.hrcore/xml/Menu/hrcore.xml
Labels: enhancement, ready to test

#2480 PCHR-3289: Fix issue with Delete button, Disable button and Delete Staff member text.
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Page/UserAccount.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/templates/CRM/HRContactActionsMenu/Page/Inline/Actions.tpl
Labels: ready to test

#2481 PCHR-3288: Link Leave Approver to contact page
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Component/ContactActionsMenu/LeaveApproversListItem.php
Labels: ready to test

#2482 PCHR-3287: Update Text and Add Divider After Record Leave Buttons
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Helper/ContactActionsMenu/LeaveActionGroup.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/BaseHeadlessTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Helper/ContactActionsMenu/LeaveActionGroupTest.php
Labels: ready to test

#2483 PCHR-3079: Hide permissions and notes field
  hrui/css/hrui.css
Labels: ready to test

#2450 PCHR-3061: Show backstop scenario label while running
  uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/init.js
  uk.co.compucorp.civicrm.hrcore/gulp/tasks/backstopjs.js
  uk.co.compucorp.civicrm.hrcore/package-lock.json
  uk.co.compucorp.civicrm.hrcore/package.json
Labels: enhancement, ready to test

#2445 PCHR-3055: Leave Balance Improvements
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-balance-tab-filters.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-balance-tab.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-balance-tab-filters.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-balance-tab.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-request-popup-details-tab.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-balance-tab-filters.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-balance-tab.html
Labels: enhancement, ready to test

#2474 PCHR-3278: Auto submit leave request comments
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-request-popup-comments-tab.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-request-popup-details-tab.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-request-popup-files-tab.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/request.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/sub-controllers/request-modal-details-leave.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/sub-controllers/request-modal-details-sickness.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/sub-controllers/request-modal-details-toil.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-request-popup-comments-tab.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-request-popup-details-tab.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-request-popup-files-tab.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/request.controller.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-popup/leave-request-popup-body.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-popup/leave-request-popup-comments-tab.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-popup/leave-request-popup-files-tab.html
Labels: enhancement, ready to test

#2484 PCHR-3260: Automate `npm install` on every CiviHR extensions
  Jenkinsfile
  package.json
  uk.co.compucorp.civicrm.appraisals/package.json
  uk.co.compucorp.civicrm.hremails/email-templates/package-lock.json
  uk.co.compucorp.civicrm.hremails/email-templates/package.json
  uk.co.compucorp.civicrm.hremails/package-lock.json
Labels: enhancement, ready to test

#2468 PCHR-3281: Fix disabled dropdown arrow in Leave Popup
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/sub-controllers/request-modal-details-leave.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/helpers/helper.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/helpers/request-modal-helper.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-request-popup-details-tab.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/sub-controllers/request-modal-details-leave.controller.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/sub-controllers/request-modal-details-sickness.controller.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/sub-controllers/request-modal-details-toil.controller.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-popup/leave-request-popup-body.html
Labels: bug, ready to test, regression

#2486 PCHR-3290: Update button text and Add Account disabled text
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Component/UserInformationLinkItem.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Helper/UserInformationActionGroup.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/tests/phpunit/CRM/HRContactActionsMenu/Helper/UserInformationActionGroupTest.php
Labels: ready to test

#2488 PCHR-3344: Fix Contact Summary Page error for a Contact without User Account
  uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.php
Labels: ready to test

#2461 PCHR-3264: Fix work pattern modal spelling
  uk.co.compucorp.civicrm.hrleaveandabsences/views/absence-tab/components/absence-tab-custom-work-pattern-modal.html
Labels: bug, ready to test

#2447 PCHR-2385: Displaying toil expiry field
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/sub-controllers/request-modal-details-toil.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/sub-controllers/request-modal-details-toil.controller.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-popup/leave-request-popup-details-tab.html
Labels: enhancement, ready to test

#2491 PCHR-3348: Include link to User role
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Component/UserRoleItem.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Helper/UserInformationActionGroup.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/css/contactactions.css
  uk.co.compucorp.civicrm.hrcontactactionsmenu/scss/components/_contact-actions.scss
Labels: enhancement, ready to test

#2496 PCHR-3355: Install Contact Actions Menu By Default
  bin/drush-install.sh
Labels: ready to test

#2497 PCHR-3349: Allow to filter the Authenticated User role.
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserRole/Drupal.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserRoleInterface.php
Labels: ready to test

#2499 PCHR-3349: Hide Authenticated Role and User ID
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Component/UserInformationLinkItem.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Component/UserRoleItem.php
Labels: ready to test

#2500 PCHR-3318: Bump version to 1.7.4
  bin/git-release.sh
  com.civicrm.hrjobroles/info.xml
  contactaccessrights/info.xml
  contactsummary/info.xml
  hrbank/info.xml
  hrcareer/info.xml
  hrcase/info.xml
  hrdemog/info.xml
  hrim/info.xml
  hrjobcontract/info.xml
  hrmed/info.xml
  hrprofile/info.xml
  hrqual/info.xml
  hrrecruitment/info.xml
  hrreport/info.xml
  hrstaffdir/info.xml
  hrui/info.xml
  org.civicrm.bootstrapcivihr/info.xml
  org.civicrm.hremergency/info.xml
  org.civicrm.reqangular/info.xml
  uk.co.compucorp.civicrm.hrcomments/info.xml
  uk.co.compucorp.civicrm.hrcore/info.xml
  uk.co.compucorp.civicrm.hremails/info.xml
  uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
  uk.co.compucorp.civicrm.hrsampledata/info.xml
Labels: ready to test

#2508 PCHR-3063: Hide leave popup details when the contact has no entitlements
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/request.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/request.controller.spec.js
Labels: bug, ready to test

#2510 PCHR-3379: Fix Error When Creating a New Site With Buildkit
  bin/drush-install.sh
Labels: ready to test

#2511 Sync master with staging
  bin/drush-install.sh
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/request.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/request.controller.spec.js
Labels: ready to test
