Repository compucorp/civihr, pull requests merged in 2018-06, with the labels that each got.

#2646 PCHR-3742: Disabling or Deleting Options Breaks Job Roles Tab
  com.civicrm.hrjobroles/js/dist/job-roles.min.js
  com.civicrm.hrjobroles/js/src/job-roles/controllers/job-roles.controller.js
Labels: ready to test

#2644 PCHR-3724: Sync styles with Shoreditch
  hrjobcontract/config.rb
  hrjobcontract/css/hrjc.css
  hrjobcontract/scss/civihr/partials/_shoreditch-imports.scss
  hrjobcontract/scss/hrjc.scss
Labels: bug, ready to test, regression

#2649 PCHR-3771: Fix months pagination
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-calendar.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-calendar.component.spec.js
Labels: bug

#2648 PCHR-3519: If Absence Type Public Label is set to true, always include Absence Type field in Leave Requests
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Handler/GenericLeaveFieldPermissions.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/API/Handler/GenericLeaveFieldPermissionsTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Labels: ready to test

#2650 PCHR-3772: Fix calendar issues with tooltips and leave request modal
  contactsummary/js/dist/contact-summary.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-notification-badge.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/apis/leave-request.api.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-calendar-month.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/apis/leave-request.api.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-calendar-month.component.spec.js
Labels: bug

#2654 PCHR-3162: Configurability Changes - Tool Icon Integration
  com.civicrm.hrjobroles/js/dist/job-roles.min.js
  com.civicrm.hrjobroles/js/src/job-roles/controllers/job-roles.controller.js
  com.civicrm.hrjobroles/views/include/add_new_role.html
  com.civicrm.hrjobroles/views/include/job_role_panel.html
  contactsummary/scss/components/_info-button.scss
  hrjobcontract/css/hrjc.css
  hrjobcontract/js/dist/job-contract.min.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-change-reason.controller.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract-new.controller.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract.controller.js
  hrjobcontract/js/src/job-contract/modules/job-contract.core.js
  hrjobcontract/js/src/job-contract/services/contract-details.service.js
  hrjobcontract/js/src/job-contract/services/contract-pay.service.js
  hrjobcontract/js/src/job-contract/services/contract-service.service.js
  hrjobcontract/js/test/controllers/modal/modal-change-reason.controller.spec.js
  hrjobcontract/js/test/controllers/modal/modal-contract-new.controller.spec.js
  hrjobcontract/js/test/controllers/modal/modal-contract.controller.spec.js
  hrjobcontract/scss/civihr/partials/_forms.scss
  hrjobcontract/templates/CRM/Hrjobcontract/Page/HoursLocation.tpl
  hrjobcontract/templates/CRM/Hrjobcontract/Page/PayScale.tpl
  hrjobcontract/views/modalChangeReason.html
  hrjobcontract/views/modalForm.html
  org.civicrm.bootstrapcivihr/css/civihr.css
  org.civicrm.bootstrapcivihr/scss/components/_help-text.scss
  org.civicrm.reqangular/dist/reqangular.min.js
  org.civicrm.reqangular/src/common/modules/templates.js
  org.civicrm.reqangular/src/common/templates/help-text.html
  org.civicrm.reqangular/test/directives/help-text.directive.spec.js
Labels: ready to test

#2655 PCHR-3785: Fix TOIL times editing
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/request.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/request.controller.spec.js
Labels: bug, ready to test, regression

#2658 PCHR-3677: Allow The Value Field For TOIL and Leave Days Amounts Option Values To Be Editable
  hrui/hrui.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/ValidateForm/AdminFormOptionsValidation.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2659 PCHR-3787: Fix postInstall hooks
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Base.php
  uk.co.compucorp.civicrm.hrcore/hrcore.civix.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Base.php
  uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.civix.php
  uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
  uk.co.compucorp.civicrm.hrsampledata/hrsampledata.php
Labels: bug, ready to test

#2661 PCHR-3781: Bump version to 1.7.7
  com.civicrm.hrjobroles/info.xml
  contactaccessrights/info.xml
  contactsummary/info.xml
  hrbank/info.xml
  hrcareer/info.xml
  hrcase/info.xml
  hrdemog/info.xml
  hrim/info.xml
  hrjobcontract/info.xml
  hrmed/info.xml
  hrprofile/info.xml
  hrqual/info.xml
  hrrecruitment/info.xml
  hrreport/info.xml
  hrstaffdir/info.xml
  hrui/info.xml
  org.civicrm.bootstrapcivihr/info.xml
  org.civicrm.hremergency/info.xml
  org.civicrm.reqangular/info.xml
  uk.co.compucorp.civicrm.hrcomments/info.xml
  uk.co.compucorp.civicrm.hrcontactactionsmenu/info.xml
  uk.co.compucorp.civicrm.hrcore/info.xml
  uk.co.compucorp.civicrm.hremails/info.xml
  uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
  uk.co.compucorp.civicrm.hrsampledata/info.xml
Labels: ready to test

#2666 PCHR-3766: Allow managers to filter by assignee type
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-calendar.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/sub-controllers/leave-calendar-manager.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/sub-controllers/leave-calendar-staff.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/services/leave-calendar.service.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/services/leave-calendar.service.mock.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-calendar.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/sub-controllers/leave-calendar-manager.controller.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/sub-controllers/leave-calendar-staff.controller.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/services/leave-calendar.service.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-calendar.html
Labels: bug, regression

#2667 PCHR-3790: Fix cost centres list error
  com.civicrm.hrjobroles/js/dist/job-roles.min.js
  com.civicrm.hrjobroles/js/src/job-roles/controllers/job-roles.controller.js
  com.civicrm.hrjobroles/js/test/controllers/job-roles.controller.spec.js
Labels: ready to test, regression

#2669 PCHR-3549: Remove primary address setter
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Pre/PrimaryAddressSetter.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2675 PCHR-3722: Fix leave requests being shown in calendar
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-calendar-month.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-calendar-month.component.spec.js
Labels: bug, ready to test

#2676 PCHR-3799: change link title in SSP and in CiviHR admin to My Account from Edit Account
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/UserMenuMarkup.tpl
Labels: ready to test

#2678 PCHR-3563: Remove unused fields from contact advanced search
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ContactAdvancedSearch.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Hook/BuildForm/ContactAdvancedSearchTest.php
Labels: enhancement, ready to test

#2680 PCHR-3636: Apply patch to CiviCRM in Jenkinsfile
  Jenkinsfile
Labels: ready to test

#2681 PCHR-3636: Make Tests more Isolated, Fix SQL Bug
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/MessageTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestMailNotificationSenderTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/MailHelpersTrait.php
Labels: ready to test

#2597 PCHR-3624: Remove HRDemog Extension
  bin/drush-install.sh
  bin/git-release.sh
  doc/INSTALL.md
  hrdemog/CRM/HRDemog/Upgrader.php
  hrdemog/CRM/HRDemog/Upgrader/Base.php
  hrdemog/hrdemog.civix.php
  hrdemog/hrdemog.php
  hrdemog/info.xml
  hrvisa/tests/phpunit/CRM/HRVisa/ActivityTest.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Page/UserMailNotifier.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/AbstractDrupalInteractionTaskForm.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Disable/CustomGroupDisabler.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Enable/CustomGroupEnabler.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Uninstall/CustomGroupRemover.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/CustomGroupStatusSwitcher.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Fabricator/CustomField.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Fabricator/CustomGroup.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1014.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1017.php
  uk.co.compucorp.civicrm.hrcore/api/v3/Job/CheckCivihrVersion.php
  uk.co.compucorp.civicrm.hrcore/config/container/container.xml
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Helper/ExtensionHelperTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/CustomGroupStatusSwitcherTest.php
  uk.co.compucorp.civicrm.hrcore/xml/CustomGroups/extended_demographics_install.xml
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/BaseCSVProcessorTest.php
Labels: ready to test

#2674 PCHR-3570: Footer Changes
  hrui/templates/CRM/common/footer.tpl
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2684 PCHR-3541: Removing Advanced Search Form Fields and Changing Some CiviCRM Settings
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ContactAdvancedSearch.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1017.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Hook/BuildForm/ContactAdvancedSearchTest.php
Labels: ready to test

#2686 PCHR-3553: Delete Phone Types
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1018.php
Labels: ready to test

#2685 PCHR-3678: my account page
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/UserMenuMarkup.tpl
Labels: ready to test

#2682 PCHR-3820: Add Leave Request ACL Rules to LeaveRequest.getAttachments API
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestAttachment.php
  uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestAttachmentTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Labels: ready to test

#2687 PCHR-3811: Update the civihr repo URL
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile
  README.md
  doc/DEVELOP.md
  doc/INSTALL.md
  doc/RELEASE.md
  doc/UPGRADE.md
  package.json
Labels: enhancement, ready to test

#2689 PCHR-3858: Add angulartics to reqangular
  org.civicrm.reqangular/build.js
  org.civicrm.reqangular/dist/reqangular.min.js
  org.civicrm.reqangular/src/common/bundles/vendors.js
  org.civicrm.reqangular/src/common/vendor/angular/angulartics-google-tag-manager.min.js
  org.civicrm.reqangular/src/common/vendor/angular/angulartics.min.js
Labels: new feature, ready to test

#2690 PCHR-3859: Add pageview tracking to L&A modules
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/admin-dashboard/app.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/admin-dashboard/modules/config.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/manager-leave/app.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/manager-leave/modules/config.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/my-leave/app.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/my-leave/modules/config.js
Labels: new feature, ready to test

#2688 PCHR-3836: Update Existing Case Types with Case Type Category
  hrcase/CRM/HRCase/Upgrader.php
Labels: ready to test

#2691 PCHR-3545: Changed Order For Individual Prefix
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1018.php
Labels: ready to test

#2694 PCHR-3611: Remove Main And Other Location Types
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1018.php
Labels: ready to test

#2693 PCHR-3875: Add tracking of virtual pageviews for contact tabs
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/js/hrcore.js
Labels: new feature, ready to test

#2692 PCHR-3836: Update Existing Case Types with Case Type
  hrcase/CRM/HRCase/Upgrader.php
Labels: ready to test

#2695 PCHR-3537: Location and Phone Type Changes
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/PageRun/LocationTypeFilter.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Pre/PrimaryAddressSetter.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1004.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1018.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1019.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrsampledata/resources/csv/civicrm_address.csv
  uk.co.compucorp.civicrm.hrsampledata/resources/csv/civicrm_email.csv
  uk.co.compucorp.civicrm.hrsampledata/resources/csv/civicrm_location_type.csv
  uk.co.compucorp.civicrm.hrsampledata/resources/csv/civicrm_phone.csv
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/Importer/LocationTypeTest.php
Labels: ready to test

#2701 PCHR-3604: Change Order Of Gender Options
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1021.php
Labels: ready to test

#2697 PCHR-3909: Fix Time Related Tests
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeExpiryLogTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php
Labels: ready to test

#2703 PCHR-3544: Hide Fields for Contact Summary
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1022.php
Labels: ready to test

#2698 PCHR-3546: Make All Currencies Available
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
Labels: ready to test

#2708 PCHR-3554: Rename Hours Location
  hrjobcontract/CRM/Hrjobcontract/Form/HoursLocation.php
  hrjobcontract/CRM/Hrjobcontract/Page/HoursLocation.php
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
  hrjobcontract/js/dist/job-contract.min.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract-new.controller.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract.controller.js
  hrjobcontract/js/test/controllers/modal/modal-contract-new.controller.spec.js
  hrjobcontract/js/test/controllers/modal/modal-contract.controller.spec.js
  hrjobcontract/templates/CRM/Hrjobcontract/Form/HoursLocation.tpl
  hrjobcontract/templates/CRM/Hrjobcontract/Page/HoursLocation.tpl
  hrjobcontract/xml/Menu/hrjobcontract.xml
Labels: ready to test

#2707 PCHR-3871: Create the LeaveRequestCalendarFeedConfig Entity
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Exception/InvalidLeaveRequestCalendarFeedConfigException.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1030.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Validator/TimeZone.php
  uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
  uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfigTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Validator/TimeZoneTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/LeaveRequestCalendarFeedConfig.entityType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/LeaveRequestCalendarFeedConfig.xml
  uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/files.xml
Labels: ready to test

#2706 PCHR-3368: Pass default status to leave request modal
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-request-actions.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/leave-request-record-actions.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/components/manage-leave-requests.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/request.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/services/leave-popup.service.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-request-actions.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/leave-request-record-actions.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/components/manage-leave-requests.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/request.controller.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/services/leave-popup.service.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-actions.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-record-actions.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/manage-leave-requests.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/staff-leave-calendar-month.html
Labels: bug, enhancement, ready to test

#2709 PCHR-3755: Fix duplicated "Localise CiviHR" menu
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1012.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1020.php
Labels: ready to test

#2713 PCHR-3391: Fix leave type in staff report after request deletion
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/partials/leave-request-dates.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/partials/staff-leave-report-requests-rows.html
Labels: bug, ready to test, regression

#2711 PCHR-3919: Show non-working days on leave calendar
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-calendar-day.html
Labels: bug, ready to test, regression

#2714 PCHR-3555: Rename Job Contract Benefit Name
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Labels: ready to test

#2710 PCHR-3911: QuickForm Error on the Localise CiviHR Page
  hrui/hrui.php
Labels: ready to test

#2716 PCHR-3556: Rename Job Contract Deduction Name
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Labels: ready to test

#2717 PCHR-3558: Rename Job Contract End Reason
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Labels: ready to test

#2715 PCHR-3557: Rename Job Contract Revision Change Reason
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Labels: ready to test

#2719 PCHR-3868: Fix js tests
  contactsummary/js/karma.conf.js
  hrjobcontract/js/karma.conf.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/karma.conf.js
Labels: bug, ready to test, regression

#2718 PCHR-3866: Administer Calendar Feeds Functionality
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1031.php
  uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.civix.php
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/LeaveRequestCalendarFeedConfig.tpl
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeedConfig.tpl
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfigTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
Labels: ready to test

#2724 PCHR-3921: Modify LeaveRequestCalendarFeedConfig Entity to Support Contact and Leave Types Filter Fields
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Wrapper/LeaveCalendarFeedFilterFields.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1030.php
  uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
  uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfigTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestCalendarFeedConfigTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/LeaveRequestCalendarFeedConfig.xml
Labels: ready to test

#2722 PCHR-3559: Delete Cost Centre Other Option
  com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Labels: ready to test
