Repository compucorp/civihr, pull requests merged in 2018-11, with the labels that each got.

#2916 PCHR-4370: Fix Issue with Staff Directory Page Not Listing Current Staff By Default
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php
Labels: ready to test

#2917 PCHR-4369: Add View and Edit To Individual Contact Actions on Staff Directory Page
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Links/ContactCustomActions.php
Labels: ready to test

#2912 PCHR-4356: Fix regression issues when syncing with latest Shoreditch release
  org.civicrm.bootstrapcivihr/css/civihr.css
  org.civicrm.bootstrapcivihr/scss/components/civihr-ui-select/_overrides.scss
Labels: ready to test

#2918 PCHR-4380: Allow meeting activity and filter by meeting activity.
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ActivityFilterSelectFieldsModifier.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ActivityLinksFilter.php
Labels: ready to test

#2920 PCHR-4328: Create Option Groups for Organization Contact in Job Role
  com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php
  com.civicrm.hrjobroles/xml/option_groups/organisation_provider_install.xml
Labels: ready to test

#2919 PCHR-4327: Create option groups for organisation contact in job contract
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
  hrjobcontract/hrjobcontract.php
  hrjobcontract/xml/option_groups/1101_departments.xml
  hrjobcontract/xml/option_groups/1105_pension_type.xml
  hrjobcontract/xml/option_groups/option_group_install.xml
  hrjobcontract/xml/option_groups/organisation_contact_install.xml
Labels: ready to test

#2924 PCHR-4335: Link Option Group to Configure Menu
  uk.co.compucorp.civicrm.hrcore/config/menu/configure.php
Labels: ready to test

#2923 PCHR-4366: Add Default Absence periods for New CiviHR installations.
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsGathererTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/PublicHolidayTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/AbsenceTypeTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/EntitlementCalculationTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveBalanceChangeTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeavePeriodEntitlementTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/PublicHolidayTest.php
Labels: ready to test

#2927 PCHR-4328: Renamed Funder Option Group API Title
  com.civicrm.hrjobroles/xml/option_groups/organisation_provider_install.xml
Labels: ready to test

#2926 PCHR-4374: Recreate missing "Open Case" activity type
  hrcase/CRM/HRCase/Upgrader.php
Labels: ready to test

#2928 PCHR-4367: Show Absence Modal for Entitlement Calculation For new Absence Periods
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsencePeriod.php
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/crm-app-form-absenceperiod.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/crm/app.form.absenceperiod.js
Labels: ready to test

#2930 PCHR-4383: Reorder Staff Directory Columns
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php
Labels: ready to test

#2922 PCHR-4381: Improve styling of Staff Directory
  org.civicrm.bootstrapcivihr/css/civihr.css
  org.civicrm.bootstrapcivihr/scss/pages/_staff-directory.scss
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/SearchCriteria.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/Selector.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectory.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryFiltersSection.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryFiltersSectionDateRange.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryResultsSection.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryResultsSectionActions.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryResultsSectionList.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryResultsSectionListPager.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryResultsSectionListPagerScript.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryTopBarSection.tpl
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Form/Search/StaffDirectoryTest.php
Labels: enhancement, ready to test

#2932 PCHR-4385: Redirect to Absence Period Listing Page After Saving Entitlements
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsencePeriod.php
Labels: ready to test

#2929 PCHR-4384: Fix Job Contract End Date Filter Bug
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Form/Search/StaffDirectoryTest.php
Labels: ready to test

#2938 PCHR-4401: Fix selector counter after submit on Staff Directory page
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectory.tpl
Labels: regression

#2940 PCHR-4401: Fix regression with bulk actions on Staff Directory
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectory.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryFiltersSection.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryTopBarSection.tpl
Labels: regression

#2921 PCHR-3987: Staff menu improvements
  com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/DataSource.php
  com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/DataSource.tpl
  hrjobcontract/CRM/Hrjobcontract/Import/Form/DataSource.php
  hrjobcontract/templates/CRM/Hrjobcontract/Import/Form/DataSource.tpl
  org.civicrm.bootstrapcivihr/css/civihr.css
  org.civicrm.bootstrapcivihr/scss/pages/_staff-directory.scss
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.mgd.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ActivityFilterSelectFieldsModifier.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ActivityLinksFilter.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ContactImportFieldsFilter.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/CustomImportFieldsFilter.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Links/ContactCustomActions.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/PreProcess/ContactForm.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Menu/Config/CustomFields.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Menu/Config/Import.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Menu/Config/StaffDirectory.php
  uk.co.compucorp.civicrm.hrcore/config/menu/configure.php
  uk.co.compucorp.civicrm.hrcore/config/menu/import.php
  uk.co.compucorp.civicrm.hrcore/config/menu/main.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectory.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryFiltersSection.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryFiltersSectionDateRange.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryResultsSection.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryResultsSectionActions.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryResultsSectionList.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryResultsSectionListPager.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryResultsSectionListPagerScript.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryTopBarSection.tpl
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Form/Search/StaffDirectoryTest.php
Labels: new feature, ready to test

#2941 PCHR-4211: Allow to edit leave types via Leave Type Wizard
  contactsummary/js/dist/contact-summary.min.js
  hrjobcontract/js/dist/job-contract.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/leave-type-wizard-form.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/manager-notification-badge.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/leave-type-wizard/components/fields-templates/leave-type-wizard-field-category.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/leave-type-wizard/components/leave-type-wizard-fields.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/leave-type-wizard/components/leave-type-wizard.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/leave-type-wizard/components/leave-type-wizard.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/leave-type-wizard/leave-type-wizard.constants.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/leave-type-wizard/leave-type-wizard.module.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/shared/models/absence-type.model.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/leave-type-wizard/components/leave-type-wizard.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/mocks/data/absence-type.data.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/shared/models/absence-type.model.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tpl
Labels: ready to test

#2942 PCHR-4331: Access Health Insurance Options Without Navigating
  hrjobcontract/js/dist/job-contract.min.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract-new.controller.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract.controller.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract.html
  hrjobcontract/js/src/job-contract/services/utils.service.js
  hrjobcontract/js/test/controllers/modal/modal-contract-new.controller.spec.js
  hrjobcontract/js/test/controllers/modal/modal-contract.controller.spec.js
  hrjobcontract/js/test/mocks/data/option-value.data.js
  hrjobcontract/js/test/services/utils.service.spec.js
Labels: ready to test

#2943 PCHR-4332: Access Life Insurance Options Without Navigating
  hrjobcontract/js/dist/job-contract.min.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract-new.controller.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract.controller.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract.html
  hrjobcontract/js/test/controllers/modal/modal-contract-new.controller.spec.js
  hrjobcontract/js/test/controllers/modal/modal-contract.controller.spec.js
Labels: ready to test

#2946 PCHR-4408: Treat Admin As Staff For Own Requests When Not Own Leave Approver
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsGathererTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrix.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrixTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
Labels: ready to test

#2948 CiviHR 1.7.13
  com.civicrm.hrjobroles/info.xml
  contactaccessrights/info.xml
  contactsummary/info.xml
  hrbank/info.xml
  hrcareer/info.xml
  hrcase/info.xml
  hrim/info.xml
  hrjobcontract/info.xml
  hrmed/info.xml
  hrprofile/info.xml
  hrqual/info.xml
  hrreport/info.xml
  hrstaffdir/info.xml
  hrui/info.xml
  org.civicrm.bootstrapcivihr/info.xml
  org.civicrm.hremergency/info.xml
  org.civicrm.reqangular/info.xml
  uk.co.compucorp.civicrm.hrcomments/info.xml
  uk.co.compucorp.civicrm.hrcontactactionsmenu/info.xml
  uk.co.compucorp.civicrm.hrcore/info.xml
  uk.co.compucorp.civicrm.hremails/info.xml
  uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
  uk.co.compucorp.civicrm.hrsampledata/info.xml
Labels: release

#2945 PCHR-4333: Access Pension Provider Options Without Navigation
  hrjobcontract/js/dist/job-contract.min.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract-new.controller.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract.controller.js
  hrjobcontract/js/src/job-contract/controllers/modal/modal-contract.html
  hrjobcontract/js/test/controllers/modal/modal-contract-new.controller.spec.js
  hrjobcontract/js/test/controllers/modal/modal-contract.controller.spec.js
Labels: ready to test

#2950 PCHR-4412: Fix error with a direct absence type enabling
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
Labels: regression

#2949 PCHR-4330: Migrate Existing Job Role Organisation Contact
  com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php
Labels: ready to test

#2952 PCHR-4417: Fix error with lost function context
  contactsummary/js/dist/contact-summary.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/shared/components/leave-widget/leave-widget.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/shared/controllers/request.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/shared/controllers/request.controller.spec.js
Labels: bug, regression

#2951 PCHR-4334: Access Funder Options Without Navigating to Settings Page
  com.civicrm.hrjobroles/js/dist/job-roles.min.js
  com.civicrm.hrjobroles/js/src/job-roles/controllers/add-new-role.html
  com.civicrm.hrjobroles/js/src/job-roles/controllers/job-role-panel.html
  com.civicrm.hrjobroles/js/src/job-roles/controllers/job-roles.controller.js
  com.civicrm.hrjobroles/js/src/job-roles/services/job-role.service.js
  com.civicrm.hrjobroles/js/test/controllers/job-roles.controller.spec.js
  com.civicrm.hrjobroles/js/test/mocks/data/job-role.data.js
Labels: ready to test

#2954 PCHR-4334: Fixed Display Issue with Existing Job Roles Funder
  com.civicrm.hrjobroles/js/src/job-roles/controllers/job-role-panel.html
Labels: ready to test

#2953 PCHR-4243: Fix AngularJS 1.6 router links
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Helper/ContactActionsMenu/WorkflowActionGroup.php
  uk.co.compucorp.civicrm.hrcore/config/menu/main.php
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/CreateUserRecordSingleTaskForm.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/CreateUserRecordTaskForm.tpl
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Files/sample_navigation_menu.json
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Message.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/MessageTest.php
Labels: regression

#2956 PCHR-4407: Improve admin non-self-approver UX
  contactsummary/js/dist/contact-summary.min.js
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsGathererTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrix.php
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/shared/components/leave-request-actions.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/shared/components/leave-widget/leave-widget.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/shared/controllers/request.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/shared/components/leave-request-actions.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/shared/controllers/request.controller.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrixTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
Labels: enhancement, ready to test

#2960 PCHR-4427: Update dependency in hremail
  uk.co.compucorp.civicrm.hremails/email-templates/package-lock.json
  uk.co.compucorp.civicrm.hremails/email-templates/package.json
  uk.co.compucorp.civicrm.hremails/package-lock.json
  uk.co.compucorp.civicrm.hremails/package.json
Labels: ready to test

#2959 PCHR-4329: Migrate existing organisation contact
  hrjobcontract/CRM/Hrjobcontract/BAO/HRJobHealth.php
  hrjobcontract/CRM/Hrjobcontract/DAO/HRJobHealth.php
  hrjobcontract/CRM/Hrjobcontract/DAO/HRJobPension.php
  hrjobcontract/CRM/Hrjobcontract/Test/Fabricator/HRJobPension.php
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
  hrjobcontract/sql/install.sql
  hrjobcontract/tests/phpunit/CRM/Hrjobcontract/Import/Parser/ApiTest.php
Labels: ready to test

#2961 PCHR-4329: Fix build issue on existing sites with foreign key constraints
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Labels: ready to test

#2962 PCHR-4329: Separated constraint checks on pension from column modification
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Labels: ready to test
