Repository compucorp/civihr, pull requests merged in 2018-07, with the labels that each got.

#2721 PCHR-3606: Remove Some Social Accounts and Reorder the Remaining
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1024.php
Labels: ready to test

#2729 PCHR-3555: Fixed Regression Issue with Adding New Benefit
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Labels: ready to test

#2725 PCHR-3849: Google Analytics Implementation - Milestone 1
  org.civicrm.reqangular/build.js
  org.civicrm.reqangular/dist/reqangular.min.js
  org.civicrm.reqangular/src/common/bundles/vendors.js
  org.civicrm.reqangular/src/common/vendor/angular/angulartics-google-tag-manager.min.js
  org.civicrm.reqangular/src/common/vendor/angular/angulartics.min.js
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/js/hrcore.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/admin-dashboard/app.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/admin-dashboard/modules/config.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/manager-leave/app.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/manager-leave/modules/config.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/my-leave/app.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/my-leave/modules/config.js
Labels: ready to test

#2730 PCHR-3556: Fixed Regression Issue with Adding Deduction
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Labels: ready to test

#2731 PCHR-3557: Fixed Regression Issue with Adding Contract Revision Reason
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Labels: ready to test

#2735 PCHR-3922: Make the Calendar Feed Administration Support Contact and Leave Types Filters
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/LeaveRequestCalendarFeedConfig.tpl
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeedConfig.tpl
Labels: ready to test

#2740 PCHR-3929: Fix JS console error if datalayer drupal module is not present/enabled
  uk.co.compucorp.civicrm.hrcore/js/hrcore.js
Labels: ready to test

#2723 PCHR-3874: Add feeds dropdown button component
  contactsummary/js/dist/contact-summary.min.js
  hrjobcontract/js/dist/job-contract.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/css/leaveandabsence.css
  uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/build.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/calendar-feeds.core.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/calendar-feeds.models.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/dropdown-button/components/calendar-feeds-dropdown-button.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/dropdown-button/components/calendar-feeds-dropdown-button.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/dropdown-button/dropdown-button.module.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/calendar-feeds.link-modal.module.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/components/calendar-feeds-link-modal.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/components/calendar-feeds-link-modal.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/directives/input-with-copy-button.directive.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/directives/input-with-copy-button.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/link-modal.constants.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/link-modal.core.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/link-modal.module.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/services/calendar-feeds-link-modal.service.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/services/apis/calendar-feed.api.data.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/services/apis/calendar-feed.api.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/services/apis/calendar-feed.api.mock.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/services/models/calendar-feed.instance.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/services/models/calendar-feed.model.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/my-leave/app.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/dropdown-button/components/calendar-feeds-dropdown-button.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/link-modal/components/calendar-feeds-link-modal.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/link-modal/directives/input-with-copy-button.directive.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/link-modal/services/calendar-feeds-link-modal.service.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/services/apis/calendar-feed.api.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/services/models/calendar-feed.instance.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/services/models/calendar-feed.model.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/globals.js
  uk.co.compucorp.civicrm.hrleaveandabsences/scss/components/_calendar-feeds.scss
  uk.co.compucorp.civicrm.hrleaveandabsences/scss/components/_leave.scss
  uk.co.compucorp.civicrm.hrleaveandabsences/views/manager-leave/components/manager-leave-container.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/my-leave/components/my-leave-container.html
Labels: new feature

#2739 PCHR-3887: Add "Add feed" button to feed dropdown
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/dropdown-button/components/calendar-feeds-dropdown-button.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/dropdown-button/components/calendar-feeds-dropdown-button.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/dropdown-button/dropdown-button.module.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/services/apis/calendar-feed.api.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/dropdown-button/components/calendar-feeds-dropdown-button.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/services/apis/calendar-feed.api.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/globals.js
Labels: new feature

#2742 PCHR-3608: Makes Contract Length Read Only
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
  hrjobcontract/xml/length_of_service.xml
Labels: ready to test

#2741 PCHR-3897: Add Calendar Feed dropdown button to Admin Dashboard
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/Dashboard.php
  uk.co.compucorp.civicrm.hrleaveandabsences/css/leaveandabsence.css
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/admin-dashboard/app.js
  uk.co.compucorp.civicrm.hrleaveandabsences/scss/pages/_admin-dashboard-page.scss
  uk.co.compucorp.civicrm.hrleaveandabsences/views/admin-dashboard/components/admin-dashboard-container.html
Labels: new feature

#2737 PCHR-3561: Change Options for Sickness Reason
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1030.php
Labels: ready to test

#2745 PCHR-3903: Implement Visibility Logic for LeaveRequestCalendarFeedConfig.get API
  com.civicrm.hrjobroles/CRM/Hrjobroles/API/Query/ContactHrJobRolesSelect.php
  com.civicrm.hrjobroles/api/v3/ContactHrJobRoles.php
  com.civicrm.hrjobroles/tests/phpunit/api/v3/ContactHRJobRoleTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/BaseHeadlessTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestCalendarFeedConfigTest.php
Labels: ready to test

#2746 PCHR-3927: Customise error message for approval transition
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
Labels: enhancement, ready to test

#2733 PCHR-3908: Display link modal on calendar feed list
  uk.co.compucorp.civicrm.hrcore/gulp/tasks/test.js
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Hook/PageRun/LeaveAndAbsencesVarsAdder.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceTab.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/Dashboard.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/build.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/calendar-feeds-list.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/calendar-feeds-list.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/components/calendar-feeds-link-modal.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/directives/input-with-copy-button.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/services/calendar-feeds-link-modal.service.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/list/directives/calendar-feeds-display-link.directive.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/list/list.core.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/list/list.module.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/dropdown-button/components/calendar-feeds-dropdown-button.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/link-modal/services/calendar-feeds-link-modal.service.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/list/directives/calendar-feeds-display-link.directive.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeedConfig.tpl
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Hook/PageRun/LeaveAndAbsencesVarsAdderTest.php
Labels: new feature, ready to test

#2748 PCHR-3947: Improve Feed Link Modal UI/UX
  contactsummary/js/dist/contact-summary.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/calendar-feeds-list.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-notification-badge.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/dropdown-button/components/calendar-feeds-dropdown-button.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/dropdown-button/components/calendar-feeds-dropdown-button.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/components/calendar-feeds-link-modal.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/components/calendar-feeds-link-modal.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/directives/input-with-copy-button.directive.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/directives/input-with-copy-button.html
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/services/calendar-feeds-link-modal.service.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/list/directives/calendar-feeds-display-link.directive.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/dropdown-button/components/calendar-feeds-dropdown-button.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/link-modal/directives/input-with-copy-button.directive.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/link-modal/services/calendar-feeds-link-modal.service.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/list/directives/calendar-feeds-display-link.directive.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeedConfig.tpl
Labels: enhancement

#2750 PCHR-3947: Make input selection work on iOS
  contactsummary/js/dist/contact-summary.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/calendar-feeds-list.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/manager-notification-badge.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/directives/input-with-copy-button.directive.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/calendar-feeds/link-modal/directives/input-with-copy-button.directive.spec.js
Labels: enhancement

#2751 PCHR-3956: Enabled is active field by default
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/PublicHoliday.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/WorkPattern.php
Labels: enhancement

#2753 PCHR-3600: Move HRDemog Fields in Contact Profile
  hrui/js/dist/hrui.min.js
  hrui/js/src/hrui.js
Labels: ready to test

#2758 PCHR-3539: Updates to Leave and Absence Settings
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1030.php
  uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql
Labels: ready to test

#2752 PCHR-3870: Provide Functionality for getting Leave Ical Feed Via URL
  uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/date.php
  uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/framework.php
  uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/ical.php
  uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/index.html
  uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/recurringdate.php
  uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/timezone.php
  uk.co.compucorp.civicrm.hrcore/vendor/icalendar/zapcallib.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Helper/CalendarFeed/LeaveTime.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeed.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedData.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedIcal.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfigTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Helper/CalendarFeed/LeaveTimeTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedDataTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedIcalTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestCalendarFeedConfigTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
Labels: ready to test

#2754 PCHR-3607: Delete Default Groups and Hides One of Them
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1026.php
Labels: ready to test

#2755 PCHR-3602 Hides disabled relationship Types from non-root admins
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/PageRun/RelationshipTypesFilter.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2759 PCHR-3839: Select Send Welcome Email by Default
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/CreateUserRecordTaskForm.php
Labels: ready to test

#2720 PCHR-3429: CiviCRM upgrade
  Jenkinsfile
  hrbank/xml/auto_install.xml
  hrcareer/xml/auto_install.xml
  hrdemog/xml/auto_install.xml
  hrident/xml/auto_install.xml
  hrjobcontract/CRM/Contact/Form/Inline/CustomData.php
  hrjobcontract/CRM/Export/BAO/Export.php
  hrjobcontract/CRM/Hrjobcontract/Dedupe/Merger.php
  hrjobcontract/CRM/Hrjobcontract/Form/Merge.php
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
  hrjobcontract/templates/CRM/Contact/Form/Inline/CustomData.tpl
  hrjobcontract/templates/CRM/Hrjobcontract/Form/Merge.hlp
  hrjobcontract/templates/CRM/Hrjobcontract/Form/Merge.tpl
  hrmed/xml/auto_install.xml
  hrqual/xml/auto_install.xml
  hrrecruitment/xml/auto_install.xml
  hrui/CRM/Core/BAO/Navigation.php
  hrui/hrui.php
  hrui/templates/CRM/Contact/Page/View/Summary.tpl
  hrui/templates/CRM/common/footer.tpl
  hrvisa/xml/auto_install.xml
  org.civicrm.hremergency/xml/auto_install.xml
  uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/templates/CRM/HRContactActionsMenu/Page/Inline/Actions.tpl
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1000.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1014.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/Role/DrupalRoleServiceTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Helper/ExtensionHelperTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Hook/BuildForm/ContactAdvancedSearchTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/DrupalUserServiceTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/FileCacheTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsCacheTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsGathererTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsJSONConvertorTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsSenderTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/WorkPattern.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1002.php
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/WorkPattern.tpl
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php
Labels: ready to test

#2762 PCHR-3975: Disable Prefer Not To Say Gender Option
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1000.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1021.php
Labels: bug, ready to test

#2765 PCHR-3542: Custom Group Updates
  bin/drush-install.sh
  bin/git-release.sh
  doc/INSTALL.md
  hrdemog/CRM/HRDemog/Upgrader.php
  hrdemog/CRM/HRDemog/Upgrader/Base.php
  hrdemog/hrdemog.civix.php
  hrdemog/hrdemog.php
  hrdemog/info.xml
  hrui/js/dist/hrui.min.js
  hrui/js/src/hrui.js
  hrvisa/tests/phpunit/CRM/HRVisa/ActivityTest.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Page/UserMailNotifier.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/AbstractDrupalInteractionTaskForm.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Disable/CustomGroupDisabler.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Enable/CustomGroupEnabler.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Uninstall/CustomGroupRemover.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/CustomGroupStatusSwitcher.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Fabricator/CustomField.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Fabricator/CustomGroup.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1021.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1025.php
  uk.co.compucorp.civicrm.hrcore/api/v3/Job/CheckCivihrVersion.php
  uk.co.compucorp.civicrm.hrcore/config/container/container.xml
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Helper/ExtensionHelperTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/CustomGroupStatusSwitcherTest.php
  uk.co.compucorp.civicrm.hrcore/xml/CustomGroups/extended_demographics_install.xml
  uk.co.compucorp.civicrm.hrsampledata/resources/csv/civicrm_option_value.csv
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/BaseCSVProcessorTest.php
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/Importer/ExtendedDemographicsTest.php
Labels: ready to test

#2769 PCHR-3979: Bump version to 1.7.8
  com.civicrm.hrjobroles/info.xml
  contactaccessrights/info.xml
  contactsummary/info.xml
  hrbank/info.xml
  hrcareer/info.xml
  hrcase/info.xml
  hrdemog/info.xml
  hrim/info.xml
  hrjobcontract/info.xml
  hrmed/info.xml
  hrprofile/info.xml
  hrqual/info.xml
  hrrecruitment/info.xml
  hrreport/info.xml
  hrstaffdir/info.xml
  hrui/info.xml
  org.civicrm.bootstrapcivihr/info.xml
  org.civicrm.hremergency/info.xml
  org.civicrm.reqangular/info.xml
  uk.co.compucorp.civicrm.hrcomments/info.xml
  uk.co.compucorp.civicrm.hrcontactactionsmenu/info.xml
  uk.co.compucorp.civicrm.hrcore/info.xml
  uk.co.compucorp.civicrm.hremails/info.xml
  uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
  uk.co.compucorp.civicrm.hrsampledata/info.xml
Labels: ready to test

#2583 PCHR-3625: Add cache parameter to relationship model and api
  org.civicrm.reqangular/dist/reqangular.min.js
  org.civicrm.reqangular/js/dist/reqangular.min.js
  org.civicrm.reqangular/js/src/common/models/relationship.model.js
  org.civicrm.reqangular/js/src/common/modules/templates.js
  org.civicrm.reqangular/js/src/common/services/api/relationship.api.js
  org.civicrm.reqangular/test/models/relationship.model.spec.js
  org.civicrm.reqangular/test/services/api/relationship.api.spec.js
Labels: enhancement, ready to test

#2779 PCHR-3957: Fix gap between logo and caption in top Civi menu
  org.civicrm.bootstrapcivihr/css/civihr.css
  org.civicrm.bootstrapcivihr/scss/civihr.scss
  org.civicrm.bootstrapcivihr/scss/overrides/_variables.scss
  org.civicrm.bootstrapcivihr/scss/overrides/crm/_link-home.scss
Labels: bug, ready to test, regression

#2780 PCHR-4001: Allow Contact to Be own Leave Approver When Assigning Leave Approver Relationship
  uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
Labels: ready to test

#2784 PCHR-3999: Hide all Civicrm System Notifications
  hrui/templates/CRM/common/footer.tpl
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2777 PCHR-3991: Use SCSS in all CiviHR Extensions
  hrcareer/css/hrcareer.css
  hrcareer/hrcareer.php
  hrident/css/hrident.css
  hrident/hrident.php
  hrmed/css/hrmed.css
  hrmed/hrmed.php
  hrqual/css/hrqual.css
  hrqual/hrqual.php
  hrui/css/hrui.css
  hrui/scss/hrui.scss
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/css/leaveandabsence.css
  uk.co.compucorp.civicrm.hrleaveandabsences/scss/leaveandabsence.scss
  uk.co.compucorp.civicrm.hrleaveandabsences/scss/vendor/_spectrum.scss
Labels: enhancement, ready to test

#2783 PCHR-3998: Fix Missing Log Tables
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1021.php
Labels: ready to test

#2787 PCHR-4026: Bump version to 1.7.9
  com.civicrm.hrjobroles/info.xml
  contactaccessrights/info.xml
  contactsummary/info.xml
  hrbank/info.xml
  hrcareer/info.xml
  hrcase/info.xml
  hrdemog/info.xml
  hrim/info.xml
  hrjobcontract/info.xml
  hrmed/info.xml
  hrprofile/info.xml
  hrqual/info.xml
  hrrecruitment/info.xml
  hrreport/info.xml
  hrstaffdir/info.xml
  hrui/info.xml
  org.civicrm.bootstrapcivihr/info.xml
  org.civicrm.hremergency/info.xml
  org.civicrm.reqangular/info.xml
  uk.co.compucorp.civicrm.hrcomments/info.xml
  uk.co.compucorp.civicrm.hrcontactactionsmenu/info.xml
  uk.co.compucorp.civicrm.hrcore/info.xml
  uk.co.compucorp.civicrm.hremails/info.xml
  uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
  uk.co.compucorp.civicrm.hrsampledata/info.xml
Labels: ready to test

#2792 PCHR-4002: Allow User Who is Own Leave Approver Take Admin Actions on Own Requests
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrix.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrixTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Labels: ready to test

#2788 PCHR-4003: Hide Recruitment Menu on Admin Portal
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1022.php
Labels: ready to test

#2775 PCHR-3941: Use RequireJS in all CiviHR extensions
  hrcareer/hrcareer.php
  hrcareer/js/build.js
  hrcareer/js/dist/hrcareer.min.js
  hrcareer/js/hrcareer.js
  hrcareer/js/src/hrcareer.js
  hrcareer/js/src/hrcareer/app.js
  hrcase/hrcase.php
  hrcase/js/hrcase.js
  hrim/hrim.php
  hrim/js/build.js
  hrim/js/dist/hrim.min.js
  hrim/js/hrim.js
  hrim/js/src/hrim.js
  hrim/js/src/hrim/app.js
  hrmed/hrmed.php
  hrmed/js/build.js
  hrmed/js/dist/hrmed.min.js
  hrmed/js/hrmed.js
  hrmed/js/src/hrmed.js
  hrmed/js/src/hrmed/app.js
  hrqual/hrqual.php
  hrqual/js/build.js
  hrqual/js/dist/hrqual.min.js
  hrqual/js/hrqual.js
  hrqual/js/src/hrqual.js
  hrqual/js/src/hrqual/app.js
  hrrecruitment/CRM/HRRecruitment/Page/CasePipeline.php
  hrui/gulp-tasks/requirejs.js
  hrui/hrui.php
  hrui/js/build.js
  hrui/js/dist/hrui.min.js
  hrui/js/src/civihr-popup/attrchange.js
  hrui/js/src/civihr-popup/civihr-popup.js
  hrui/js/src/contact.js
  hrui/js/src/hrui.js
  hrui/js/src/hrui/civihr-popup/attrchange.js
  hrui/js/src/hrui/civihr-popup/civihr-popup.js
  hrui/js/src/hrui/contact.js
  hrui/js/src/hrui/main.js
  org.civicrm.reqangular/js/build.js
  org.civicrm.reqangular/js/dist/reqangular.min.js
  org.civicrm.reqangular/js/src/common/bundles/vendors.js
  org.civicrm.reqangular/reqangular.php
  package-lock.json
  uk.co.compucorp.civicrm.hrcontactactionsmenu/css/contactactions.css
  uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/js/build.js
  uk.co.compucorp.civicrm.hrcontactactionsmenu/js/contactactions.js
  uk.co.compucorp.civicrm.hrcontactactionsmenu/js/dist/contact-actions.min.js
  uk.co.compucorp.civicrm.hrcontactactionsmenu/js/src/contact-actions.js
  uk.co.compucorp.civicrm.hrcontactactionsmenu/js/src/contact-actions/app.js
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Page/Reports.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/js/build.js
  uk.co.compucorp.civicrm.hrcore/js/dist/hrcore.min.js
  uk.co.compucorp.civicrm.hrcore/js/hrcore.js
  uk.co.compucorp.civicrm.hrcore/js/src/hrcore.js
  uk.co.compucorp.civicrm.hrcore/js/src/hrcore/app.js
  uk.co.compucorp.civicrm.hrcore/js/src/hrcore/vendor/iframeResizer.min.js
  uk.co.compucorp.civicrm.hrcore/package-lock.json
Labels: enhancement, ready to test

#2795 PCHR-4040: Allow user who is own Leave Approver to delete own requet
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
Labels: ready to test

#2797 PCHR-3624: Migrating Custom Groups
  bin/drush-install.sh
  bin/git-release.sh
  hrdemog/CRM/HRDemog/Upgrader.php
  hrdemog/CRM/HRDemog/Upgrader/Base.php
  hrdemog/hrdemog.civix.php
  hrdemog/hrdemog.php
  hrdemog/info.xml
  hrvisa/tests/phpunit/CRM/HRVisa/ActivityTest.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Page/UserMailNotifier.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/AbstractDrupalInteractionTaskForm.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Disable/CustomGroupDisabler.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Enable/CustomGroupEnabler.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Uninstall/CustomGroupRemover.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/CustomGroupStatusSwitcher.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Fabricator/CustomField.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Fabricator/CustomGroup.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1022.php
  uk.co.compucorp.civicrm.hrcore/api/v3/Job/CheckCivihrVersion.php
  uk.co.compucorp.civicrm.hrcore/config/container/container.xml
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Helper/ExtensionHelperTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/CustomGroupStatusSwitcherTest.php
  uk.co.compucorp.civicrm.hrcore/xml/CustomGroups/extended_demographics_install.xml
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/BaseCSVProcessorTest.php
Labels: ready to test

#2778 PCHR-3345: Unable to Create User Account for Restored Contact
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/CreateUserRecordTaskForm.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/DrupalUserService.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/DrupalUserServiceTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/drupal_function_mocks.php
Labels: ready to test

#2798 PCHR-3599: Remove HR Demog Custom Fields
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1023.php
  uk.co.compucorp.civicrm.hrcore/xml/CustomGroups/extended_demographics_install.xml
  uk.co.compucorp.civicrm.hrsampledata/resources/csv/civicrm_option_value.csv
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/Importer/ExtendedDemographicsTest.php
Labels: ready to test

#2802 PCHR-3542: Custom Group Updates
  bin/drush-install.sh
  bin/git-release.sh
  hrdemog/CRM/HRDemog/Upgrader.php
  hrdemog/CRM/HRDemog/Upgrader/Base.php
  hrdemog/hrdemog.civix.php
  hrdemog/hrdemog.php
  hrdemog/info.xml
  hrdemog/xml/auto_install.xml
  hrui/js/dist/hrui.min.js
  hrui/js/src/hrui/main.js
  hrvisa/tests/phpunit/CRM/HRVisa/ActivityTest.php
  uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Page/UserMailNotifier.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/AbstractDrupalInteractionTaskForm.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Disable/CustomGroupDisabler.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Enable/CustomGroupEnabler.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Uninstall/CustomGroupRemover.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/CustomGroupStatusSwitcher.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Fabricator/CustomField.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Fabricator/CustomGroup.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1022.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1023.php
  uk.co.compucorp.civicrm.hrcore/api/v3/Job/CheckCivihrVersion.php
  uk.co.compucorp.civicrm.hrcore/config/container/container.xml
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Helper/ExtensionHelperTest.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/CustomGroupStatusSwitcherTest.php
  uk.co.compucorp.civicrm.hrcore/xml/CustomGroups/extended_demographics_install.xml
  uk.co.compucorp.civicrm.hrsampledata/resources/csv/civicrm_option_value.csv
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/BaseCSVProcessorTest.php
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/Importer/ExtendedDemographicsTest.php
Labels: ready to test

#2805 PCHR-4051: Allow Own Approver And Admin Cancel Own Leave Request Even When Absence Type Does Not Allow It
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Labels: ready to test
