Repository compucorp/civihr, pull requests merged in 2018-08, with the labels that each got.

#2808 PCHR-4054: Allow Own Leave Approver Edit Leave Dates For Own Request.
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php
Labels: ready to test

#2807 PCHR-4076: Fix Filters on Admin Leave - Leave Requests and Calendar Tab
  com.civicrm.hrjobroles/CRM/Hrjobroles/API/Query/ContactHrJobRolesSelect.php
  com.civicrm.hrjobroles/CRM/Hrjobroles/Test/Fabricator/HrJobRoles.php
  com.civicrm.hrjobroles/tests/phpunit/api/v3/ContactHRJobRoleTest.php
Labels: ready to test

#2785 PCHR-3997: Allow own leave approver
  org.civicrm.reqangular/js/dist/reqangular.min.js
  org.civicrm.reqangular/js/dist/reqangular.mocks.min.js
  org.civicrm.reqangular/js/src/common/models/contact.js
  org.civicrm.reqangular/js/src/common/models/instances/contact-instance.js
  org.civicrm.reqangular/js/src/common/modules/templates.js
  org.civicrm.reqangular/js/test/helpers/globals.helper.js
  org.civicrm.reqangular/js/test/mocks/models/instances/session-mock.js
  org.civicrm.reqangular/js/test/models/contact.spec.js
  org.civicrm.reqangular/js/test/models/instances/contact-instance.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrix.php
  uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/absence-tab.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/admin-dashboard.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/manager-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/my-leave.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/shared/components/leave-request-actions.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/shared/components/staff-leave-report.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/shared/controllers/request.controller.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/shared/components/leave-request-actions.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/shared/components/staff-leave-report.component.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/shared/controllers/request.controller.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrixTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-actions.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-popup/leave-request-popup-body.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-popup/leave-request-popup-footer.html
  uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/partials/staff-leave-report-requests-rows.html
Labels: new feature, ready to test

#2810 SHOR-22: Remove extra PHP code for appending contact image - covered under shoreditch
  hrui/hrui.php
Labels: enhancement, ready to test

#2814 PCHR-4003: Hide Recruitment Menu in Admin Portal
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1022.php
Labels: ready to test

#2813 PCHR-4075: Fix Filters on Admin - Advanced Search - Job Role Filters
  com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/Query.php
Labels: ready to test

#2804 PCHR-4049: Upgrade gulp
  Jenkinsfile
  package-lock.json
  uk.co.compucorp.civicrm.hrcore/gulp/tasks/requirejs.js
  uk.co.compucorp.civicrm.hrcore/gulp/tasks/sass.js
  uk.co.compucorp.civicrm.hrcore/gulp/tasks/test.js
  uk.co.compucorp.civicrm.hrcore/gulpfile.js
  uk.co.compucorp.civicrm.hrcore/package-lock.json
  uk.co.compucorp.civicrm.hrcore/package.json
Labels: enhancement, ready to test

#2812 PCHR-4005: Fix icons in HRMed and HRCareer forms
  hrcareer/js/build.js
  hrcareer/js/dist/hrcareer.min.js
  hrcareer/js/src/hrcareer/app.js
  hrmed/js/build.js
  hrmed/js/dist/hrmed.min.js
  hrmed/js/src/hrmed/app.js
  uk.co.compucorp.civicrm.hrcore/hrcore.php
  uk.co.compucorp.civicrm.hrcore/js/dist/hrcore.min.js
  uk.co.compucorp.civicrm.hrcore/js/src/hrcore/analytics.js
  uk.co.compucorp.civicrm.hrcore/js/src/hrcore/app.js
  uk.co.compucorp.civicrm.hrcore/js/src/hrcore/helpers.js
Labels: bug, ready to test, regression

#2819 PCHR-4049: Fix gulp tasks
  uk.co.compucorp.civicrm.hrcore/gulp/tasks/requirejs.js
  uk.co.compucorp.civicrm.hrcore/gulp/tasks/sass.js
  uk.co.compucorp.civicrm.hrcore/gulp/tasks/test.js
  uk.co.compucorp.civicrm.hrcore/gulp/utils.js
  uk.co.compucorp.civicrm.hrcore/gulpfile.js
Labels: bug, regression

#2760 PCHR-3536: Display Preferences
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
  hrjobcontract/xml/length_of_service.xml
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/PageRun/RelationshipTypesFilter.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1000.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1024.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1025.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1026.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1027.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1028.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1029.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1030.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2818 PCHR-4098: Misc BackstopJS fixes and improvements
  uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/ssp-my-details.js
  uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/la-dashboard.json
  uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-la-manager.json
  uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-la-my-leave.json
  uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ta-calendar.json
  uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ta-documents.json
  uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ta-tasks.json
  uk.co.compucorp.civicrm.hrcore/package-lock.json
  uk.co.compucorp.civicrm.hrcore/package.json
Labels: enhancement, ready to test, regression

#2821 PCHR-3963: Fix SSP Filters to Take into Account Role Start End Dates
  com.civicrm.hrjobroles/CRM/Hrjobroles/API/Query/ContactHrJobRolesSelect.php
  com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/Query.php
  com.civicrm.hrjobroles/CRM/Hrjobroles/Test/Fabricator/HrJobRoles.php
  com.civicrm.hrjobroles/tests/phpunit/api/v3/ContactHRJobRoleTest.php
Labels: ready to test

#2816 PCHR-4050: Fix Case Type Category upgraders
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1031.php
Labels: ready to test, regression

#2823 PCHR-4110: Fix calendar feeds leave requests inclusion logic
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedData.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedDataTest.php
Labels: bug, ready to test

#2822 PCHR-4072: Update help link to lead to freshdesk knowledge base
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2827 PCHR-3797: Improve Apply Core Fork Patch Script to Avoid API Rate Limit Errors
  bin/apply-core-fork-patch.sh
Labels: ready to test

#2828 PCHR-4046: Fix security vulnerabilities
  hrui/package-lock.json
  hrui/package.json
  org.civicrm.bootstrapcivihr/css/civihr.css
  org.civicrm.bootstrapcivihr/package-lock.json
  org.civicrm.bootstrapcivihr/package.json
  org.civicrm.bootstrapcivihr/scss/civihr.scss
  org.civicrm.reqangular/gulp-tasks/requirejs.js
  org.civicrm.reqangular/package-lock.json
  org.civicrm.reqangular/package.json
  package-lock.json
  uk.co.compucorp.civicrm.hrcore/gulp/tasks/sass.js
  uk.co.compucorp.civicrm.hrcore/package-lock.json
  uk.co.compucorp.civicrm.hrcore/package.json
  uk.co.compucorp.civicrm.hremails/email-templates/package-lock.json
  uk.co.compucorp.civicrm.hremails/email-templates/package.json
  uk.co.compucorp.civicrm.hremails/package-lock.json
  uk.co.compucorp.civicrm.hrleaveandabsences/css/leaveandabsence.css
  uk.co.compucorp.civicrm.hrleaveandabsences/package-lock.json
  uk.co.compucorp.civicrm.hrleaveandabsences/package.json
Labels: enhancement, ready to test

#2829 PCHR-3625: Add relationship type model, instance, api service, and mock data
  org.civicrm.reqangular/js/build.mocks.js
  org.civicrm.reqangular/js/dist/reqangular.min.js
  org.civicrm.reqangular/js/dist/reqangular.mocks.min.js
  org.civicrm.reqangular/js/src/common/bundles/apis.js
  org.civicrm.reqangular/js/src/common/bundles/models.js
  org.civicrm.reqangular/js/src/common/models/instances/relationship-type.instance.js
  org.civicrm.reqangular/js/src/common/models/relationship-type.model.js
  org.civicrm.reqangular/js/src/common/services/api/relationship-type.js
  org.civicrm.reqangular/js/test/mocks/data/relationship-type.data.js
  org.civicrm.reqangular/js/test/mocks/services/api/relationship-type-mock.js
  org.civicrm.reqangular/js/test/models/instances/relationship-type.instance.spec.js
  org.civicrm.reqangular/js/test/models/relationship-type.model.spec.js
  org.civicrm.reqangular/js/test/services/api/relationship-type.spec.js
  package-lock.json
  uk.co.compucorp.civicrm.hrcore/package-lock.json
Labels: new feature, ready to test

#2830 PCHR-3410: Change default assignee option labels
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1032.php
Labels: enhancement, ready to test

#2831 PCHR-4116: Bump version to 1.7.10
  com.civicrm.hrjobroles/info.xml
  contactaccessrights/info.xml
  contactsummary/info.xml
  hrbank/info.xml
  hrcareer/info.xml
  hrcase/info.xml
  hrim/info.xml
  hrjobcontract/info.xml
  hrmed/info.xml
  hrprofile/info.xml
  hrqual/info.xml
  hrrecruitment/info.xml
  hrreport/info.xml
  hrstaffdir/info.xml
  hrui/info.xml
  org.civicrm.bootstrapcivihr/info.xml
  org.civicrm.hremergency/info.xml
  org.civicrm.reqangular/info.xml
  uk.co.compucorp.civicrm.hrcomments/info.xml
  uk.co.compucorp.civicrm.hrcontactactionsmenu/info.xml
  uk.co.compucorp.civicrm.hrcore/info.xml
  uk.co.compucorp.civicrm.hremails/info.xml
  uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
  uk.co.compucorp.civicrm.hrsampledata/info.xml
Labels: ready to test

#2835 PCHR-4061: Allow Passing Contact Subtype as a Parameter
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/DataSourceFilter.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2836 PCHR-4059: Improve Staff Menu
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1032.php
Labels: ready to test

#2824 PCHR-4101: Remove Recruitment Submenus
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1032.php
Labels: ready to test

#2838 PCHR-4131: Hide Import Menus From Staff Menu
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1032.php
Labels: ready to test

#2839 PCHR-4132: Add the Correct Menu Link to New Meeting
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1032.php
Labels: ready to test

#2842 PCHR-4139: Remove HRRecruitment For New Sites
  Jenkinsfile
  bin/civihr-crm-api-tests.sh
  bin/civihr-webtests.sh
  bin/drush-install.sh
  bin/git-release.sh
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/Stats/StatsGatherer.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/BaseHeadlessTest.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1031.php
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/BaseCSVProcessorTest.php
Labels: ready to test

#2843 PCHR-4138: The link is wrong
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2846 PCHR-4063: Changing Import Contacts to Import Staff
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2815 PCHR-3930: Uninstall HR-Recruitment Extension
  Jenkinsfile
  bin/civihr-crm-api-tests.sh
  bin/civihr-webtests.sh
  bin/drush-install.sh
  bin/git-release.sh
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/Stats/StatsGatherer.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/BaseHeadlessTest.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1031.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1032.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsGathererTest.php
  uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/BaseCSVProcessorTest.php
Labels: ready to test

#2837 PCHR-4055: Staff Menu Changes
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1033.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1034.php
Labels: ready to test

#2848 PCHR-4150: Grant HR Admin access to message template menu
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1033.php
Labels: ready to test

#2776 PCHR-3369: Tasks & Workflows UX improvements
  hrcase/CRM/HRCase/Upgrader.php
  org.civicrm.reqangular/dist/reqangular.min.js
  org.civicrm.reqangular/js/build.mocks.js
  org.civicrm.reqangular/js/dist/reqangular.min.js
  org.civicrm.reqangular/js/dist/reqangular.mocks.min.js
  org.civicrm.reqangular/js/src/common/bundles/apis.js
  org.civicrm.reqangular/js/src/common/bundles/models.js
  org.civicrm.reqangular/js/src/common/models/instances/relationship-type.instance.js
  org.civicrm.reqangular/js/src/common/models/instances/relationship.instance.js
  org.civicrm.reqangular/js/src/common/models/relationship-type.model.js
  org.civicrm.reqangular/js/src/common/models/relationship.model.js
  org.civicrm.reqangular/js/src/common/services/api/relationship-type.js
  org.civicrm.reqangular/js/src/common/services/api/relationship.api.js
  org.civicrm.reqangular/js/test/mocks/data/relationship-type.data.js
  org.civicrm.reqangular/js/test/mocks/services/api/relationship-type-mock.js
  org.civicrm.reqangular/js/test/models/instances/relationship-type.instance.spec.js
  org.civicrm.reqangular/js/test/models/relationship-type.model.spec.js
  org.civicrm.reqangular/js/test/services/api/relationship-type.spec.js
  org.civicrm.reqangular/test/mocks/data/relationship.data.js
  org.civicrm.reqangular/test/mocks/services/api/relationship.api.mock.js
  org.civicrm.reqangular/test/models/instances/relationship.instance.spec.js
  org.civicrm.reqangular/test/models/relationship.model.spec.js
  org.civicrm.reqangular/test/services/api/relationship.api.spec.js
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1031.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1033.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1034.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1035.php
Labels: enhancement, ready to test

#2852 PCHR-3369: Fix return value for upgrader
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1034.php
Labels: bug, ready to test, regression
