Repository compucorp/civihr, pull requests merged in 2018-10, with the labels that each got.

#2871 PCHR-4148: Fix issue with blank/incorrect display of Contract length of service field
  hrjobcontract/CRM/Hrjobcontract/Upgrader.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ContactFormCustomGroupFilter.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/PageRun/ContactSummaryCustomGroupFilter.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test, regression

#2873 PCHR-4173: Local Admin Role is not available
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/CreateUserRecordTaskForm.php
Labels: ready to test

#2870 PCHR-4213: Add Category Field to Leave Type
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/AbsencePeriod.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/ContactWorkPattern.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeaveBalanceChange.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeaveBalanceChangeExpiryLog.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeavePeriodEntitlement.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeavePeriodEntitlementLog.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeaveRequestCalendarFeedConfig.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeaveRequestDate.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/NotificationReceiver.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/PublicHoliday.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/WorkDay.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/WorkPattern.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/WorkWeek.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1034.php
  uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/absence_type_category_install.xml
  uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/AbsenceType.xml
Labels: ready to test

#2877 PCHR-4241: Fix bootstrap logic of contact access rights's angular app
  contactaccessrights/js/dist/access-rights.min.js
  contactaccessrights/js/src/access-rights.js
  uk.co.compucorp.civicrm.hrcontactactionsmenu/js/dist/contact-actions.min.js
  uk.co.compucorp.civicrm.hrcontactactionsmenu/js/src/contact-actions/app.js
Labels: bug, ready to test, regression

#2876 PCHR-3039: Allow admins to change Absence Type of open Leave Requests
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php
Labels: bug, ready to test

#2878 PCHR-4207: Add leave type category label
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tpl
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
Labels: ready to test

#2881 PCHR-4217: Remove is-default option from leave type list
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1035.php
  uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tpl
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/AbsenceType.xml
Labels: ready to test

#2882 PCHR-4217: Removed other references to is_default
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/crm-app-list-absenceperiod.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/dist/crm-app-list.min.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/crm/app.list.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/mocks/data/absence-type.data.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/shared/apis/absence-type.api.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/shared/instances/absence-type.instance.spec.js
Labels: ready to test

#2885 PCHR-4278: Transform leave type webform to page
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/AbsenceType.tpl
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tpl
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/AbsenceType/FormTest.php
Labels: ready to test

#2886 PCHR-4302: Remove Search Menu and Sub Items
  uk.co.compucorp.civicrm.hrcore/config/menu/main.php
Labels: ready to test

#2887 PCHR-4303: Modify Staff Menu Items
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/PreProcess/ContactForm.php
  uk.co.compucorp.civicrm.hrcore/config/menu/main.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2888 CiviHR 1.7.12
  com.civicrm.hrjobroles/info.xml
  contactaccessrights/info.xml
  contactsummary/info.xml
  hrbank/info.xml
  hrcareer/info.xml
  hrcase/info.xml
  hrim/info.xml
  hrjobcontract/info.xml
  hrmed/info.xml
  hrprofile/info.xml
  hrqual/info.xml
  hrreport/info.xml
  hrstaffdir/info.xml
  hrui/info.xml
  org.civicrm.bootstrapcivihr/info.xml
  org.civicrm.hremergency/info.xml
  org.civicrm.reqangular/info.xml
  uk.co.compucorp.civicrm.hrcomments/info.xml
  uk.co.compucorp.civicrm.hrcontactactionsmenu/info.xml
  uk.co.compucorp.civicrm.hrcore/info.xml
  uk.co.compucorp.civicrm.hremails/info.xml
  uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
  uk.co.compucorp.civicrm.hrsampledata/info.xml
Labels: release

#2889 PCHR-4304: Move Import related Items to the Configure menu.
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Menu/Config/CustomFields.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Menu/Config/Import.php
  uk.co.compucorp.civicrm.hrcore/config/menu/configure.php
  uk.co.compucorp.civicrm.hrcore/config/menu/import.php
Labels: ready to test

#2890 PCHR-4305: Filter Unwanted Fields From Import Contact Screen.
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ContactImportFieldsFilter.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2892 PCHR-4306: Filter Unwanted Fields From Job Roles/Job Contract Import Page
  com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/DataSource.php
  com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/DataSource.tpl
  hrjobcontract/CRM/Hrjobcontract/Import/Form/DataSource.php
  hrjobcontract/templates/CRM/Hrjobcontract/Import/Form/DataSource.tpl
Labels: ready to test

#2894 PCHR-4308: Update Import Contact Page Title
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2897 PCHR-4217: Schema Fixes for Absence Type Log Table
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1035.php
Labels: ready to test

#2898 PCHR-4345: Improve Absence Type Title Validation
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/AbsenceTypeTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Labels: ready to test

#2902 PCHR-4207: Add Leave Type Category Label
  uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tpl
Labels: ready to test

#2901 PCHR-4311: Create Staff Directory Search Page
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.mgd.php
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/SearchCriteria.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/Selector.tpl
  uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectory.tpl
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Form/Search/StaffDirectoryTest.php
Labels: ready to test

#2903 PCHR-4310: Modify Bulk Actions After Search for Staff Directory Page
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php
  uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Form/Search/StaffDirectoryTest.php
Labels: ready to test

#2906 PCHR-4317: Add menu URL for staff directory.
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Menu/Config/StaffDirectory.php
  uk.co.compucorp.civicrm.hrcore/config/menu/main.php
Labels: ready to test

#2905 PCHR-4309: Modify Search Actions for Individual Contacts on Staff Directory Page
  uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Links/ContactCustomActions.php
  uk.co.compucorp.civicrm.hrcore/hrcore.php
Labels: ready to test

#2884 PCHR-4249: Existing Leave Types to be Working after Upgrade
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1036.php
Labels: ready to test

#2911 PCHR-4350: Existing Sickness Leave Request Migration
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1037.php
Labels: ready to test
