Repository compucorp/civihr, pull requests merged in 2018-12, with the labels that each got.

#2965 PCHR-4426: Fix warning on the Work Patterns list page
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/ContactWorkPatternTest.php
Labels: bug, ready to test

#2939 PCHR-4396: Fix "creating default object from empty value" warning on the SSP
  hrjobcontract/api/v3/HRJobContract.php
Labels: ready to test

#2967 PCHR-4441: Fix errors on the L&A settings page
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/GeneralSettings.php
Labels: bug, ready to test

#2958 PCHR-4243: Fix error handling and UX on Contact Summary
  contactsummary/css/contactsummary.css
  contactsummary/js/dist/contact-summary.min.js
  contactsummary/js/src/contact-summary/controllers/key-dates.controller.js
  contactsummary/js/src/contact-summary/controllers/key-dates.html
  contactsummary/js/src/contact-summary/controllers/key-details.html
  contactsummary/js/src/contact-summary/services/job-role.service.js
  contactsummary/js/test/controllers/key-dates.controller.spec.js
  contactsummary/scss/contactsummary.scss
  org.civicrm.reqangular/js/dist/reqangular.min.js
  org.civicrm.reqangular/js/dist/reqangular.mocks.min.js
  org.civicrm.reqangular/js/src/common/models/contract.js
  org.civicrm.reqangular/js/src/common/models/instances/job-role-instance.js
  org.civicrm.reqangular/js/src/common/models/job-role.js
  org.civicrm.reqangular/js/src/common/modules/templates.js
  org.civicrm.reqangular/js/src/common/services/api/job-role.js
  org.civicrm.reqangular/js/test/mocks/services/api/job-role-mock.js
  org.civicrm.reqangular/js/test/models/contract.spec.js
  org.civicrm.reqangular/js/test/models/job-role.spec.js
  org.civicrm.reqangular/js/test/services/api/job-role.spec.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/shared/components/leave-widget/leave-widget.component.js
  uk.co.compucorp.civicrm.hrleaveandabsences/js/test/shared/components/leave-widget/leave-widget.component.spec.js
Labels: bug, enhancement, ready to test

#2968 PCHR-4432: Add support for creation of Public Holiday Requests for Absence Types with MTPHL Via Background Job
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletion.php
  uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/PublicHolidayLeaveRequest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php
  uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php
Labels: ready to test

#2971 CiviHR 1.7.14
  com.civicrm.hrjobroles/info.xml
  contactaccessrights/info.xml
  contactsummary/info.xml
  hrbank/info.xml
  hrcareer/info.xml
  hrcase/info.xml
  hrim/info.xml
  hrjobcontract/info.xml
  hrmed/info.xml
  hrprofile/info.xml
  hrqual/info.xml
  hrreport/info.xml
  hrstaffdir/info.xml
  hrui/info.xml
  org.civicrm.bootstrapcivihr/info.xml
  org.civicrm.hremergency/info.xml
  org.civicrm.reqangular/info.xml
  uk.co.compucorp.civicrm.hrcomments/info.xml
  uk.co.compucorp.civicrm.hrcontactactionsmenu/info.xml
  uk.co.compucorp.civicrm.hrcore/info.xml
  uk.co.compucorp.civicrm.hremails/info.xml
  uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
  uk.co.compucorp.civicrm.hrsampledata/info.xml
Labels: release

#2899 PCHR-4346: CiviCRM Upgrade
  Jenkinsfile
  hrjobcontract/CRM/Export/BAO/Export.php
  hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContractRevision.php
  hrjobcontract/CRM/Hrjobcontract/Dedupe/Merger.php
  hrjobcontract/templates/CRM/Hrjobcontract/Form/Merge.tpl
  hrui/CRM/Core/BAO/Navigation.php
  hrui/hrui.php
  hrui/templates/CRM/Contact/Page/Inline/Basic.tpl
  hrui/templates/CRM/Contact/Page/View/Summary.tpl
Labels: ready to test

#2973 PCHR-4446: Fix Expected Variable Reference Warning
  uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
Labels: ready to test

#2974 PCHR-4448: Fix Warning and Notice Messages on Import Job Contract Wizard
  hrjobcontract/CRM/Hrjobcontract/Import/Parser.php
  hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php
  hrjobcontract/CRM/Hrjobcontract/Import/Parser/BaseClass.php
Labels: ready to test

#2979 PCHR-4444: Funders of Type Individual is not saved with the correct Contact ID
  com.civicrm.hrjobroles/CRM/Hrjobroles/DAO/HrJobRoles.php
  com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php
Labels: ready to test
